### ISSUE TITLE
Нужна возможность определения прав доступа в некоторых случаях вне гема

### ISSUE THREAD

**Issue by madding** [7Pikes/flexible_accessibility#12]
Пример: есть раздел на который нужно давать права доступа, но также в раздел можно заходить пользователям по прямой ссылке с определенным токеном в урле.

В данной ситуации помог бы модификатор :if

  authorize :only => [:index], :if => :token_nil?

**Comment by mochnatiy** [comment]
Ты хочешь давать доступ в раздел незалогиненному пользователю?

**Comment by undr** [comment]
лучше добавить авторизацию по токену, а права проверять как и раньше

**Comment by mochnatiy** [comment]
+1 Логичное решение

**Comment by mochnatiy** [comment]
Отключение проверки для отдельного экшена для незалогиненного пользователя в 0.3.1 есть.

**Comment by madding** [comment]
В моем случае там не токен юзера, а токен аптеки

**Comment by mochnatiy** [comment]
Для аптеки есть аутентификация по токену в разделе синков, можно ее использовать вкупе со скипом проверки из версии 0.3.1. В итоге получается, что нужно скипать в случае, если current_user => nil, а в остальных случаях проверять. Подумаю.

**Comment by madding** [comment]
current_user => nil и token present?

и конкретно в моем случае не надо авторизовывать ни юзера ни аптеку нужно просто показать данные по аптеке тому у кого есть заветная прямая ссылка, как pastie.org

**Comment by mochnatiy** [comment]
Токен джему не нужен, токен - это аутентификация, это задача софта понять, кто ломится за данными. Задача джема - авторизация, понять можно ли давать данные. Я могу скипнуть проверку по current_user => nil, а ты уже закроешь ресурс аутентификацией аптеки. На многих ресурсах у гостей один доступ к функционалу, а у аутентифицированных пользователей - другой.

**Comment by madding** [comment]
:+1:

**Comment by mochnatiy** [comment]
На данный момент, после тестов и размышлений, могу сказать что задача должна быть реализована на стороне приложения.

**Comment by madding** [comment]
Для того чтобы реализовать на стороне приложения, нужно скипнуть авторизацию при определенном условии (когда например приходит токен аптечный в урле), есть такая возможность ?

**Comment by mochnatiy** [comment]
Библиотека дополнительных опций не принимает, макрос работает чисто в декларативном стиле. Для тебя очень гибкий вариант - это аутентификация по токену, создание guest- пользователя (или abstract- пользователя, как удобнее), присвоение ему необходимых пермишенов и присвоение этого пользователя в переменную current_user.

**Comment by mochnatiy** [comment]
В 0.3.16 добавлены макросы allow_route и deny_route для возможности доступа в случае нестандартных кондишенов.
