### ISSUE TITLE
authorize :only => :symbol

### ISSUE THREAD

**Issue by pospeev** [7Pikes/flexible_accessibility#8]
Хочется иметь служебные значения для authorize :only в контроллере.
Чтобы можно было записать так:

``` ruby
authorize :only => :all
```

Соответственно, это применялось бы ко всем экшенам.

**Comment by pospeev** [comment]
Блин, я это уже просил: https://github.com/7Pikes/flexible_accessibility/issues/3

**Comment by mochnatiy** [comment]
authorize => :all
